# Generated by Django 5.0.1 on 2024-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('hospital_type', models.CharField(choices=[('General Hospital', 'General Hospital'), ('Specialty Hospital', 'Specialty Hospital'), ('Community Hospital', 'Community Hospital'), ('Corporate Hospital', 'Corporate Hospital')], max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('hospital_image', models.ImageField(upload_to='hospital_images/')),
                ('address', models.TextField()),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_status', models.BooleanField(default='pending')),
            ],
        ),
    ]
