# Generated by Django 5.0.1 on 2024-02-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='otp_status',
            field=models.BooleanField(default='Not Verified'),
        ),
    ]
