# Generated by Django 5.0.1 on 2024-02-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_alter_hospital_otp_alter_hospital_otp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Injection', 'Injection'), ('Ointment', 'Ointment')], max_length=50)),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_description', models.TextField()),
                ('stock_size', models.IntegerField()),
                ('medicine_image', models.ImageField(upload_to='medicine_images/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospital')),
            ],
        ),
    ]
