# Generated by Django 5.0.1 on 2024-02-04 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_medicine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
