# Generated by Django 5.0.1 on 2024-02-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_alter_medicine_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('General Bed', 'General Bed'), ('ICU Bed', 'ICU Bed'), ('Pediatric Bed', 'Pediatric Bed'), ('Specialized Bed', 'Specialized Bed')], max_length=50)),
                ('bed_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bed_description', models.TextField()),
                ('num_beds_available', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospital')),
            ],
        ),
    ]
