# Generated by Django 5.0.1 on 2024-02-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_diagnosticservice_emergencyservice_surgicalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=64)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.medicine')),
            ],
        ),
    ]
