# Generated by Django 5.0.1 on 2024-02-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_medicineblockchain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineBlockchain',
        ),
    ]
