# Generated by Django 5.0.1 on 2024-02-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_delete_medicineblockchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineid', models.CharField(max_length=100)),
                ('medicine_price', models.CharField(max_length=100)),
                ('medicine_type', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalapp.medicine')),
            ],
            options={
                'db_table': 'blockchainmodel',
            },
        ),
    ]
