# Generated by Django 5.0.1 on 2024-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_bkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkmodel',
            name='medicine_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
