# Generated by Django 5.0.1 on 2024-02-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_alter_bkmodel_medicine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkmodel',
            name='medicine_price',
            field=models.CharField(max_length=100),
        ),
    ]
