# Generated by Django 5.0.1 on 2024-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0016_hospital_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_doc',
            field=models.ImageField(null=True, upload_to='hospital_document_images/'),
        ),
    ]
