# Generated by Django 5.0.1 on 2024-02-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_for', models.CharField(max_length=10)),
                ('service_required', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency')], max_length=20)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hospital', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
