# Generated by Django 5.0.1 on 2024-02-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_diagnosticservice_emergencyservice_surgicalservice'),
        ('userapp', '0005_hospitalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='users', to='hospitalapp.medicine'),
        ),
    ]
