# Generated by Django 5.0.1 on 2024-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_user_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreport',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
