# Generated by Django 5.0.1 on 2024-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0015_alter_medicine_medicine_price'),
        ('userapp', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='medicine_ids',
        ),
        migrations.AddField(
            model_name='cart',
            name='medicine_ids',
            field=models.ManyToManyField(blank=True, to='hospitalapp.medicine'),
        ),
    ]
