# Generated by Django 5.0.1 on 2024-02-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_cart_medicine_ids_cart_medicine_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
