# Generated by Django 5.0.1 on 2024-02-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_cart_cartmedicine_cart_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmedicine',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartmedicine',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartMedicine',
        ),
    ]
