# Generated by Django 5.0.1 on 2024-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_cartmedicine_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
