# Generated by Django 5.0.1 on 2024-02-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_cartitem_hospital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreport',
            name='unethical_staff_name',
            field=models.CharField(blank=True, default='No name', max_length=100, null=True),
        ),
    ]
