# Generated by Django 5.0.1 on 2024-02-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_hospitalreport_unethical_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreport',
            name='unethical_staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
