# Generated by Django 5.0.1 on 2024-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_hospitalreport_unethical_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='accepted', max_length=10),
        ),
    ]
