# Generated by Django 5.0.1 on 2024-02-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_hospitalreport_unethical_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreport',
            name='unethical_staff_name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
